# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='title',
            field=models.CharField(default='Default Track', help_text='Track Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(default='Default Session', max_length=50),
        ),
        migrations.AlterField(
            model_name='track',
            name='session',
            field=models.ForeignKey(help_text='Session', on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
        ),
    ]
