# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 01:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170527_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(default='default-session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='owner',
            field=models.ForeignKey(default=None, help_text='Owner', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='session',
            field=models.ForeignKey(help_text='Session', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.Session'),
        ),
    ]
