# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_track_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='url',
        ),
        migrations.AddField(
            model_name='track',
            name='track_id',
            field=models.CharField(default='', help_text='Spotify Track ID', max_length=20),
        ),
    ]
