# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170701_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='title',
        ),
    ]
