# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 01:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_remove_track_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='owner',
            field=models.ForeignKey(default=None, help_text='Owner', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.Profile'),
        ),
    ]
