# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170706_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25)),
                ('added_date', models.DateTimeField()),
                ('joined_session', models.CharField(max_length=100)),
            ],
        ),
    ]
